# Generated by Django 3.2 on 2021-12-27 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_body_review_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='approved',
        ),
    ]
