# Generated by Django 3.2 on 2021-12-29 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_rename_job_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='job_type',
            field=models.IntegerField(choices=[(0, 'Plumber'), (1, 'Electrical'), (2, 'Small Repairs'), (3, 'Flooring'), (4, 'Painting'), (5, 'Other')]),
        ),
    ]
