# Generated by Django 3.2 on 2021-12-31 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_worker_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='job_type',
            field=models.IntegerField(choices=[(0, 'Plumber'), (1, 'Electrical'), (2, 'Small Repairs'), (3, 'Flooring'), (4, 'Painting'), (5, 'Cleaner'), (6, 'Other')]),
        ),
    ]
