# Generated by Django 3.2 on 2022-01-01 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0006_alter_worker_job_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('small_description', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('job_type', models.IntegerField(choices=[(0, 'Plumber'), (1, 'Electrical'), (2, 'Small Repairs'), (3, 'Flooring'), (4, 'Painting'), (5, 'Cleaner'), (6, 'Other')])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_author', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='job_like', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('author'), nulls_last=True)],
            },
        ),
        migrations.AlterField(
            model_name='review',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='website.publication'),
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
