# Generated by Django 3.2 on 2022-01-02 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_publication_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='job_type',
            field=models.IntegerField(choices=[(0, 'Plumber'), (1, 'Electrical'), (2, 'Small Repairs'), (3, 'Flooring'), (4, 'Painting'), (5, 'Cleaner'), (6, 'Other')]),
        ),
    ]
