# Generated by Django 3.2 on 2022-01-04 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_publication_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='author_id',
            field=models.IntegerField(default=1, verbose_name='Author ID'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='author',
            field=models.CharField(max_length=200),
        ),
    ]
