# Generated by Django 3.2 on 2022-01-04 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20220104_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='author',
        ),
        migrations.AddField(
            model_name='publication',
            name='author_fname',
            field=models.CharField(default='admin', max_length=200, verbose_name='First Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='author_lname',
            field=models.CharField(default='admin', max_length=200, verbose_name='Last Name'),
            preserve_default=False,
        ),
    ]
